### PR TITLE
Added an option to wait or not

### PR DESCRIPTION
**Pull request by thomaspicquet**

### CODE REVIEW

**Comment by davedevelopment** [comment]
What's the use case here?

**Comment by aequasi** [comment]
Similar reason to my issue. Would like to kill the request (rate limit), instead of wait (throttle), if the limits are hit.

**Comment by thomaspicquet** [comment]
Yup exactly, when the there's a wait I just send a 429 response with the time they have to wait

**Comment by davedevelopment** [comment]
Ok, I'm not keen on introducing a boolean parameter that changes behaviour, it's not something I'd ever use and is I'd consider it a code smell as well. I'm not against adding some sort of convenience method that acts as a facade to the existing API as mentioned in #9.

**Comment by aequasi** [comment]
Well, I'm sure others would use it (as seen evident by this pull request), and i find that forcing to sleep is actually more of a code smell than just returning how long it should sleep for. That seems like something that should be left up to the user, not forced upon them.

**Comment by aequasi** [comment]
Just as an example: If there is a rate limit for an endpoint on an API that should only be hit twice an hour, i don't think its a really good idea for the process to be sleeping for 59 minutes. This really should be baked into the core, and avoided with a workaround.

**Comment by tuupola** [comment]
I agree with @davedevelopment that adding a boolean flag which changes method behaviour is bad API design. I think current issue is more about documentation. You can already use `getEstimate()` to see if you hit ratelimit without waiting. Method name is maybe a bit counter intuitive for this purpose and it is not documented, but you still can do it.

**Comment by aequasi** [comment]
again, the issue pointed out, is that `getEstimate` doesn't increase the counter. Sleeping inside a vendor lib seems like a really dangerous idea to me...

**Comment by thomaspicquet** [comment]
I'll let you update it the way you want, without the boolean ;) thanks

**Comment by davedevelopment** [comment]
> Well, I'm sure others would use it (as seen evident by this pull request), and i find that forcing to sleep is actually more of a code smell than just returning how long it should sleep for. That seems like something that should be left up to the user, not forced upon them.

I'm not totally against it, I said that boolean arguments are a code smell and I wouldn't change the behaviour of this method with one. I'd disagree that it's forced upon them, the `getEstimate` method is there for this purpose. The `getEstimate` method gives you an estimate of how long it will wait for, the throttle method actually does it and increments the counter.

> Just as an example: If there is a rate limit for an endpoint on an API that should only be hit twice an hour, i don't think its a really good idea for the process to be sleeping for 59 minutes. This really should be baked into the core, and avoided with a workaround.

That might be true if the library had been built for that use case, but it wasn't. This library was built for throttling a socket server client, sharing a quota with several other processes that needed close to millisecond accuracy. 

I think what we have already is a reasonable low level API, something wrapping it or alongside it would do nicely for your purposes. 

> I agree with @davedevelopment that adding a boolean flag which changes method behaviour is bad API design. I think current issue is more about documentation. You can already use getEstimate() to see if you hit ratelimit without waiting. Method name is maybe a bit counter intuitive for this purpose and it is not documented, but you still can do it.

Agree that the method naming isn't ideal, will consider adding an alias.

> Sleeping inside a vendor lib seems like a really dangerous idea to me...

I don't think it's unreasonable, but I am happy to have it be configurable via something more than boolean argument on a method (which is also part of a contract).

Be it in the form of callbacks, some sort of object, I don't mind, as long as the default behaviour remains and the API remains the same.

**Comment by thomaspicquet** [comment]
For now I'll keep using my version without sleep(), I think you should just remove that, I started to use the library to protect my site against brute force attacks and if you make the PHP process wait, its just a recipe for disaster.

**Pull request closed without merging**
